version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - server-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  server:
    working_dir: /workspace/ReactorCore-TP2_SI
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: mvn spring-boot:run
    env_file: .env
    networks:
      - server-network
    volumes:
      - ..:/workspace
    user: root
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  server-network:
